services:
  db:
    image: postgres
    container_name: example-postgres
    env_file:
      - ./db/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./db/init:/docker-entrypoint-initdb.d

  api:
    build:
      context: ./api
    container_name: example-api
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data: 