services:
  postgres:
    image: postgres
    container_name: example-postgres
    env_file:
      - ./db/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./db/init:/docker-entrypoint-initdb.d

volumes:
  postgres_data: